### ISSUE TITLE
Needs a License

### ISSUE THREAD

**Issue by dgovil** [LumaPictures/cg-stubs#2]
Hey Chad, would it be possible to put up a license for use of the stubs? Just so that folks can get it cleared for use. 

Thanks!

**Comment by chadrik** [comment]
Hey Dhruv,  each of the generated stubs on PyPI should have its own MIT license, but I went ahead and added an Apache 2.0 license to this project as well to cover the code generators.  I used Apache in case this eventually gets rolled into USD. I also just pushed up some improved instructions for building the USD stubs.

**Comment by dgovil** [comment]
Awesome thank you!
